ffmpeg -i video/FAUSA_01.mp4 -i final/01.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_01_46 Linden Street.mkv"
ffmpeg -i video/FAUSA_02.mp4 -i final/02.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_02_The Blind Date.mkv"
ffmpeg -i video/FAUSA_03.mp4 -i final/03.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_03_Grandpa's Trunk.mkv"
ffmpeg -i video/FAUSA_04.mp4 -i final/04.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_04_A Piece of Cake.mkv"
ffmpeg -i video/FAUSA_05.mp4 -i final/05.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_05_The Right Magic.mkv"
ffmpeg -i video/FAUSA_06.mp4 -i final/06.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_06_Thanksgiving.mkv"
ffmpeg -i video/FAUSA_07.mp4 -i final/07.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_07_Man's Best Friend.mkv"
ffmpeg -i video/FAUSA_08.mp4 -i final/08.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_08_You're Going to Be Fine.mkv"
ffmpeg -i video/FAUSA_09.mp4 -i final/09.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_09_It's Up to You.mkv"
ffmpeg -i video/FAUSA_10.mp4 -i final/10.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_10_Smell the Flowers.mkv"
ffmpeg -i video/FAUSA_11.mp4 -i final/11.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_11_A Place of Our Own.mkv"
ffmpeg -i video/FAUSA_12.mp4 -i final/12.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_12_You're Tops.mkv"
ffmpeg -i video/FAUSA_13.mp4 -i final/13.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_13_A Real Stewart.mkv"
ffmpeg -i video/FAUSA_14.mp4 -i final/14.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_14_Playing Games.mkv"
ffmpeg -i video/FAUSA_15.mp4 -i final/15.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_15_Second Honeymoon.mkv"
ffmpeg -i video/FAUSA_16.mp4 -i final/16.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_16_Full of Surprises.mkv"
ffmpeg -i video/FAUSA_17.mp4 -i final/17.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_17_Photo Finish.mkv"
ffmpeg -i video/FAUSA_18.mp4 -i final/18.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_18_Making a Difference.mkv"
ffmpeg -i video/FAUSA_19.mp4 -i final/19.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_19_I Do.mkv"
ffmpeg -i video/FAUSA_20.mp4 -i final/20.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_20_Quality Time.mkv"
ffmpeg -i video/FAUSA_21.mp4 -i final/21.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_21_A Big Fish in a Little Pond.mkv"
ffmpeg -i video/FAUSA_22.mp4 -i final/22.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_22_Career Choices.mkv"
ffmpeg -i video/FAUSA_23.mp4 -i final/23.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_23_The Community Center.mkv"
ffmpeg -i video/FAUSA_24.mp4 -i final/24.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_24_Parting Friends.mkv"
ffmpeg -i video/FAUSA_25.mp4 -i final/25.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_25_Country Music.mkv"
ffmpeg -i video/FAUSA_26.mp4 -i final/26.srt -c:v libx265 -tag:v hvc1 -filter:v unsharp -c:a copy -c:s srt "video/FAUSA_26_Opening Night.mkv"

